import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const PAGE = {
  margin: 14,
  width: 210,
  height: 297,
  bottomSafe: 18,
};

const COLORS = {
  navy: [15, 23, 42],
  navySoft: [30, 41, 59],
  blue: [30, 64, 175],
  blueSoft: [239, 246, 255],
  amber: [245, 158, 11],
  amberSoft: [255, 251, 235],
  green: [22, 101, 52],
  greenSoft: [240, 253, 244],
  slate: [71, 85, 105],
  slateLight: [100, 116, 139],
  lightSlate: [241, 245, 249],
  pageBg: [248, 250, 252],
  border: [226, 232, 240],
  white: [255, 255, 255],
};

const formatValue = (value, fallback = "Not provided") => {
  if (value === 0) return "0";
  if (!value || String(value).trim() === "") return fallback;
  return String(value).trim();
};

const formatStatusLabel = (status) => {
  if (!status) return "Pending";
  return String(status).charAt(0).toUpperCase() + String(status).slice(1);
};

const formatRoleLabel = (role) => {
  if (!role) return "Worker";

  const roleMap = {
    lead: "Lead",
    worker: "Worker",
    helper: "Helper",
    supervisor: "Supervisor",
    admin: "Admin",
  };

  const normalizedRole = String(role).trim().toLowerCase();

  if (roleMap[normalizedRole]) {
    return roleMap[normalizedRole];
  }

  return String(role)
    .replace(/_/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
};

const formatTeamMember = (member, index) => {
  const name =
    member?.fullName ||
    member?.full_name ||
    member?.name ||
    member?.email ||
    `Team member ${index + 1}`;

  const email = member?.email || "";
  const role = member?.roleOnJob || member?.role_on_job || member?.role || "";
  const roleText = role ? formatRoleLabel(role) : "Worker";

  return email ? `${name} · ${email} · ${roleText}` : `${name} · ${roleText}`;
};

const formatDate = (dateValue) => {
  if (!dateValue) return "Not provided";

  const date = new Date(`${dateValue}T00:00:00`);

  if (Number.isNaN(date.getTime())) {
    const fallbackDate = new Date(dateValue);

    if (Number.isNaN(fallbackDate.getTime())) {
      return dateValue;
    }

    return fallbackDate.toLocaleDateString("en-AU", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  }

  return date.toLocaleDateString("en-AU", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};

const formatDateTime = (dateValue) => {
  if (!dateValue) return "Not provided";

  const date = new Date(dateValue);

  if (Number.isNaN(date.getTime())) {
    return "Not provided";
  }

  return date.toLocaleString("en-AU", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

const formatTime = (timeValue) => {
  if (!timeValue) return "Not provided";
  return String(timeValue).slice(0, 5);
};

const getStatusColor = (status) => {
  if (status === "completed") return COLORS.green;
  if (status === "checked") return COLORS.blue;
  return COLORS.amber;
};

const getStatusSoftColor = (status) => {
  if (status === "completed") return COLORS.greenSoft;
  if (status === "checked") return COLORS.blueSoft;
  return COLORS.amberSoft;
};

const safeFileName = (value) => {
  return String(value || "job-report")
    .replace(/[^a-z0-9-_]+/gi, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
};

const drawPageBackground = (doc) => {
  doc.setFillColor(...COLORS.pageBg);
  doc.rect(0, 0, PAGE.width, PAGE.height, "F");
};

const ensureSpace = (doc, y, neededHeight = 30) => {
  if (y + neededHeight > PAGE.height - PAGE.bottomSafe) {
    doc.addPage();
    drawPageBackground(doc);
    return 20;
  }

  return y;
};

const addPageFooter = (doc, pageNumber, totalPages, reportData) => {
  const reportNumber = formatValue(reportData.reportNumber, "Job report");

  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.2);
  doc.line(
    PAGE.margin,
    PAGE.height - 14,
    PAGE.width - PAGE.margin,
    PAGE.height - 14
  );

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...COLORS.slate);

  doc.text(
    `Generated by JobProof · ${reportNumber}`,
    PAGE.margin,
    PAGE.height - 8
  );

  doc.text(
    `Page ${pageNumber} of ${totalPages}`,
    PAGE.width - PAGE.margin,
    PAGE.height - 8,
    { align: "right" }
  );
};

const addSectionTitle = (doc, title, subtitle, y) => {
  y = ensureSpace(doc, y, subtitle ? 18 : 12);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12.5);
  doc.setTextColor(...COLORS.navy);
  doc.text(title, PAGE.margin, y);

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.slate);
    doc.text(subtitle, PAGE.margin, y + 5);
    return y + 10;
  }

  return y + 7;
};

const addTwoColumnTable = (doc, title, subtitle, rows, y, options = {}) => {
  const cleanRows = rows.filter((row) => {
    return row.some((cell) => cell !== undefined && cell !== null);
  });

  if (!cleanRows.length) return y;

  y = addSectionTitle(doc, title, subtitle, y);

  autoTable(doc, {
    startY: y,
    head: options.showHead === false ? undefined : [["Field", "Details"]],
    body: cleanRows,
    theme: "grid",
    margin: {
      left: PAGE.margin,
      right: PAGE.margin,
    },
    pageBreak: "auto",
    rowPageBreak: "avoid",
    styles: {
      font: "helvetica",
      fontSize: options.fontSize || 8.2,
      cellPadding: options.cellPadding || 2.7,
      textColor: COLORS.navy,
      lineColor: COLORS.border,
      lineWidth: 0.2,
      valign: "top",
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: COLORS.navy,
      textColor: COLORS.white,
      fontStyle: "bold",
      fontSize: 8,
    },
    columnStyles: {
      0: {
        cellWidth: options.firstColumnWidth || 44,
        fontStyle: "bold",
        fillColor: COLORS.lightSlate,
        textColor: COLORS.navy,
      },
      1: {
        cellWidth: "auto",
        textColor: COLORS.navy,
      },
    },
    didDrawPage: () => {
      drawPageBackground(doc);
    },
  });

  return doc.lastAutoTable.finalY + (options.afterGap || 8);
};

const addSummaryCard = (
  doc,
  x,
  y,
  width,
  title,
  value,
  accentColor = COLORS.blue
) => {
  doc.setFillColor(...COLORS.white);
  doc.setDrawColor(...COLORS.border);
  doc.roundedRect(x, y, width, 25, 3, 3, "FD");

  doc.setFillColor(...accentColor);
  doc.roundedRect(x, y, 3, 25, 2, 2, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.slate);
  doc.text(String(title).toUpperCase(), x + 7, y + 8);

  const valueLines = doc.splitTextToSize(formatValue(value), width - 10);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.navy);
  doc.text(valueLines.slice(0, 2), x + 7, y + 15);
};

const addTextBox = (doc, title, text, y) => {
  const cleanText = formatValue(text, "No details provided.");
  const maxWidth = PAGE.width - PAGE.margin * 2;
  const lines = doc.splitTextToSize(cleanText, maxWidth - 9);
  const boxHeight = Math.max(25, lines.length * 4.5 + 15);

  y = ensureSpace(doc, y, boxHeight + 14);
  y = addSectionTitle(doc, title, null, y);

  doc.setDrawColor(...COLORS.border);
  doc.setFillColor(...COLORS.white);
  doc.roundedRect(PAGE.margin, y, maxWidth, boxHeight, 3, 3, "FD");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.8);
  doc.setTextColor(...COLORS.navy);
  doc.text(lines, PAGE.margin + 4.5, y + 8);

  return y + boxHeight + 9;
};

const convertImageToDataUrl = async (imageUrl) => {
  if (!imageUrl || typeof imageUrl !== "string") return null;

  if (imageUrl.startsWith("data:image")) {
    return imageUrl;
  }

  try {
    const response = await fetch(imageUrl, {
      mode: "cors",
      cache: "force-cache",
    });

    if (!response.ok) return null;

    const blob = await response.blob();

    return await new Promise((resolve) => {
      const reader = new FileReader();

      reader.onloadend = () => {
        resolve(reader.result);
      };

      reader.onerror = () => {
        resolve(null);
      };

      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.warn("Could not load image for PDF:", error);
    return null;
  }
};

const getImageType = (imageData) => {
  if (typeof imageData !== "string") return "JPEG";
  if (imageData.startsWith("data:image/png")) return "PNG";
  return "JPEG";
};

const addImageToBox = (doc, imageData, x, y, width, height) => {
  if (!imageData) return false;

  try {
    doc.addImage(imageData, getImageType(imageData), x, y, width, height);
    return true;
  } catch {
    try {
      doc.addImage(imageData, "JPEG", x, y, width, height);
      return true;
    } catch {
      try {
        doc.addImage(imageData, "PNG", x, y, width, height);
        return true;
      } catch (error) {
        console.warn("Could not add image to PDF:", error);
        return false;
      }
    }
  }
};

const addPhotoCard = async (doc, photoUrl, photoNumber, x, y, width, height) => {
  const imageData = await convertImageToDataUrl(photoUrl);

  doc.setDrawColor(...COLORS.border);
  doc.setFillColor(...COLORS.white);
  doc.roundedRect(x, y, width, height, 3, 3, "FD");

  doc.setFillColor(...COLORS.navy);
  doc.roundedRect(x + 3, y + 3, 12, 7, 2, 2, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.white);
  doc.text(String(photoNumber).padStart(2, "0"), x + 9, y + 8, {
    align: "center",
  });

  if (imageData) {
    const added = addImageToBox(
      doc,
      imageData,
      x + 4,
      y + 13,
      width - 8,
      height - 17
    );

    if (added) return;
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.slate);
  doc.text("Image could not be loaded.", x + 8, y + 34);
};

const addPhotoGrid = async (doc, title, photos = [], y) => {
  const validPhotos = photos.filter(Boolean);

  if (!validPhotos.length) {
    return y;
  }

  const imageWidth = 84;
  const imageHeight = 61;
  const gap = 10;
  const rowHeight = imageHeight + 10;
  const titleHeight = 15;
  const firstSectionHeight = titleHeight + rowHeight;
  const leftX = PAGE.margin;
  const rightX = PAGE.margin + imageWidth + gap;

  const drawTitle = (currentY, isContinuation = false) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12.5);
    doc.setTextColor(...COLORS.navy);
    doc.text(title, PAGE.margin, currentY);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.slate);
    doc.text(
      isContinuation
        ? "Continued photographic evidence."
        : "Photographic evidence attached to this job report.",
      PAGE.margin,
      currentY + 5
    );

    return currentY + titleHeight;
  };

  if (y + firstSectionHeight > PAGE.height - PAGE.bottomSafe) {
    doc.addPage();
    drawPageBackground(doc);
    y = 20;
  }

  y = drawTitle(y, false);

  for (let index = 0; index < validPhotos.length; index += 2) {
    if (y + rowHeight > PAGE.height - PAGE.bottomSafe) {
      doc.addPage();
      drawPageBackground(doc);
      y = 20;

      if (y + firstSectionHeight <= PAGE.height - PAGE.bottomSafe) {
        y = drawTitle(y, true);
      }
    }

    await addPhotoCard(
      doc,
      validPhotos[index],
      index + 1,
      leftX,
      y,
      imageWidth,
      imageHeight
    );

    if (validPhotos[index + 1]) {
      await addPhotoCard(
        doc,
        validPhotos[index + 1],
        index + 2,
        rightX,
        y,
        imageWidth,
        imageHeight
      );
    }

    y += rowHeight;
  }

  return y + 4;
};

const addHeader = async (doc, reportData) => {
  drawPageBackground(doc);

  doc.setFillColor(...COLORS.navy);
  doc.roundedRect(PAGE.margin, 12, PAGE.width - PAGE.margin * 2, 43, 4, 4, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(19);
  doc.setTextColor(...COLORS.white);
  doc.text("JobProof", PAGE.margin + 8, 25);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(219, 234, 254);
  doc.text("Professional job completion report", PAGE.margin + 8, 32);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.white);
  doc.text(
    formatValue(reportData.reportNumber, "Report number pending"),
    PAGE.margin + 8,
    43
  );

  const status = reportData.status || "pending";
  const statusColor = getStatusColor(status);

  doc.setFillColor(...statusColor);
  doc.roundedRect(PAGE.width - PAGE.margin - 48, 20, 38, 10, 2.5, 2.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...COLORS.white);
  doc.text(
    formatStatusLabel(status).toUpperCase(),
    PAGE.width - PAGE.margin - 29,
    26.5,
    { align: "center" }
  );

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(203, 213, 225);
  doc.text(
    `Generated ${formatDateTime(new Date().toISOString())}`,
    PAGE.width - PAGE.margin - 10,
    43,
    { align: "right" }
  );

  if (reportData.businessLogo) {
    const logoData = await convertImageToDataUrl(reportData.businessLogo);

    if (logoData) {
      doc.setFillColor(...COLORS.white);
      doc.roundedRect(PAGE.width - PAGE.margin - 45, 32, 35, 14, 2, 2, "F");
      addImageToBox(doc, logoData, PAGE.width - PAGE.margin - 42, 34, 29, 10);
    }
  }

  return 66;
};

const addReportSummary = (doc, reportData, y) => {
  y = addSectionTitle(
    doc,
    "Report summary",
    "Quick overview of the job and current status.",
    y
  );

  const cardWidth = 42.5;
  const gap = 5;
  const startX = PAGE.margin;

  addSummaryCard(
    doc,
    startX,
    y,
    cardWidth,
    "Client",
    reportData.clientDisplayName || reportData.clientName,
    COLORS.blue
  );

  addSummaryCard(
    doc,
    startX + cardWidth + gap,
    y,
    cardWidth,
    "Job date",
    formatDate(reportData.jobDate),
    COLORS.amber
  );

  addSummaryCard(
    doc,
    startX + (cardWidth + gap) * 2,
    y,
    cardWidth,
    "Hours",
    formatValue(reportData.totalHours, "0"),
    COLORS.green
  );

  addSummaryCard(
    doc,
    startX + (cardWidth + gap) * 3,
    y,
    cardWidth,
    "Status",
    formatStatusLabel(reportData.status || "pending"),
    getStatusColor(reportData.status || "pending")
  );

  return y + 34;
};

const addStatusNotice = (doc, reportData, y) => {
  const status = reportData.status || "pending";
  const color = getStatusColor(status);
  const softColor = getStatusSoftColor(status);
  const maxWidth = PAGE.width - PAGE.margin * 2;

  const noticeText =
    status === "completed"
      ? "This report has been marked as completed and is ready for client review."
      : status === "checked"
      ? "This report has been checked and is awaiting final completion."
      : "This report is currently pending review.";

  y = ensureSpace(doc, y, 20);

  doc.setFillColor(...softColor);
  doc.setDrawColor(...color);
  doc.roundedRect(PAGE.margin, y, maxWidth, 16, 3, 3, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.2);
  doc.setTextColor(...color);
  doc.text(noticeText, PAGE.margin + 5, y + 10);

  return y + 24;
};

export const generatePDF = async (reportData = {}) => {
  const doc = new jsPDF("p", "mm", "a4");

  let y = await addHeader(doc, reportData);

  y = addReportSummary(doc, reportData, y);
  y = addStatusNotice(doc, reportData, y);

  y = addTwoColumnTable(
    doc,
    "Business details",
    "Company information attached to this report.",
    [
      ["Business name", formatValue(reportData.businessName)],
      ["Business email", formatValue(reportData.businessEmail)],
      ["Business phone", formatValue(reportData.businessPhone)],
      ["Prepared by", formatValue(reportData.workerName)],
    ],
    y,
    {
      fontSize: 8.1,
      cellPadding: 2.4,
      afterGap: 8,
    }
  );

  y = addTwoColumnTable(
    doc,
    "Client and job details",
    "Client, location and job scheduling information.",
    [
      [
        "Client",
        formatValue(reportData.clientDisplayName || reportData.clientName),
      ],
      ["Client company", formatValue(reportData.clientCompanyName)],
      ["Contact person", formatValue(reportData.clientContactPerson)],
      ["Client email", formatValue(reportData.clientEmail)],
      ["Client phone", formatValue(reportData.clientPhone)],
      [
        "Job address",
        formatValue(reportData.clientAddressSnapshot || reportData.jobAddress),
      ],
      ["Access notes", formatValue(reportData.clientAccessNotes)],
      ["Job date", formatDate(reportData.jobDate)],
      ["Start time", formatTime(reportData.startingHour)],
      ["Finish time", formatTime(reportData.finishHour)],
      ["Total hours", formatValue(reportData.totalHours, "0")],
      ["Service type", formatValue(reportData.serviceType)],
    ],
    y,
    {
      fontSize: 8,
      cellPadding: 2.25,
      afterGap: 8,
    }
  );

  const teamRows =
    reportData.teamInvolved && reportData.teamInvolved.length > 0
      ? reportData.teamInvolved.map((member, index) => [
          `Team member ${index + 1}`,
          formatTeamMember(member, index),
        ])
      : [["Team involved", "No team members listed."]];

  addTwoColumnTable(
    doc,
    "Team involved",
    "People attached to this job report.",
    teamRows,
    y,
    {
      fontSize: 8,
      cellPadding: 2.4,
      afterGap: 8,
    }
  );

  doc.addPage();
  drawPageBackground(doc);
  y = 20;

  y = addTextBox(doc, "Work completed", reportData.workCompleted, y);
  y = addTextBox(doc, "Issues found", reportData.issuesFound, y);
  y = addTextBox(doc, "Recommendations", reportData.recommendations, y);

  const hasBeforePhotos =
    reportData.beforePhotos && reportData.beforePhotos.length > 0;
  const hasAfterPhotos =
    reportData.afterPhotos && reportData.afterPhotos.length > 0;

  if (hasBeforePhotos && hasAfterPhotos) {
    const afterPhotosStartY = await addPhotoGrid(
      doc,
      "Before photos",
      reportData.beforePhotos,
      y
    );

    await addPhotoGrid(
      doc,
      "After photos",
      reportData.afterPhotos,
      afterPhotosStartY
    );
  } else if (hasBeforePhotos) {
    await addPhotoGrid(doc, "Before photos", reportData.beforePhotos, y);
  } else if (hasAfterPhotos) {
    await addPhotoGrid(doc, "After photos", reportData.afterPhotos, y);
  } else {
    const photoSectionY = addSectionTitle(
      doc,
      "Photo evidence",
      null,
      ensureSpace(doc, y, 32)
    );

    doc.setFillColor(...COLORS.white);
    doc.setDrawColor(...COLORS.border);
    doc.roundedRect(
      PAGE.margin,
      photoSectionY,
      PAGE.width - PAGE.margin * 2,
      22,
      3,
      3,
      "FD"
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...COLORS.slate);
    doc.text(
      "No before or after photos were attached to this report.",
      PAGE.margin + 5,
      photoSectionY + 12
    );
  }

  const totalPages = doc.internal.getNumberOfPages();

  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    addPageFooter(doc, page, totalPages, reportData);
  }

  const fileName = `${safeFileName(reportData.reportNumber || "job-report")}.pdf`;

  doc.save(fileName);
};
