import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const PAGE = {
  margin: 14,
  width: 210,
  height: 297,
};

const COLORS = {
  navy: [15, 23, 42],
  blue: [30, 64, 175],
  amber: [245, 158, 11],
  green: [22, 101, 52],
  slate: [71, 85, 105],
  lightSlate: [241, 245, 249],
  border: [226, 232, 240],
  white: [255, 255, 255],
};

const formatValue = (value, fallback = "Not provided") => {
  if (value === 0) return "0";
  if (!value || String(value).trim() === "") return fallback;
  return String(value).trim();
};

const formatStatusLabel = (status) => {
  if (!status) return "Pending";
  return String(status).charAt(0).toUpperCase() + String(status).slice(1);
};

const formatRoleLabel = (role) => {
  if (!role) return "";

  const roleMap = {
    lead: "Lead",
    worker: "Worker",
    helper: "Helper",
    supervisor: "Supervisor",
    admin: "Admin",
  };

  const normalizedRole = String(role).trim().toLowerCase();

  if (roleMap[normalizedRole]) {
    return roleMap[normalizedRole];
  }

  return String(role)
    .replace(/_/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
};

const formatTeamMember = (member) => {
  const name =
    member?.fullName ||
    member?.full_name ||
    member?.name ||
    member?.email ||
    "Team member";

  const role =
    member?.roleOnJob ||
    member?.role_on_job ||
    member?.role ||
    "";

  const cleanRole = formatRoleLabel(role);

  if (!cleanRole) return name;

  return `${name} — ${cleanRole}`;
};

const formatDate = (dateValue) => {
  if (!dateValue) return "Not provided";

  const date = new Date(dateValue);

  if (Number.isNaN(date.getTime())) {
    return dateValue;
  }

  return date.toLocaleDateString("en-AU", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};

const formatTime = (timeValue) => {
  if (!timeValue) return "Not provided";
  return String(timeValue).slice(0, 5);
};

const getStatusColor = (status) => {
  if (status === "completed") return COLORS.green;
  if (status === "checked") return COLORS.blue;
  return COLORS.amber;
};

const safeFileName = (value) => {
  return String(value || "job-report")
    .replace(/[^a-z0-9-_]+/gi, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
};

const addPageFooter = (doc, pageNumber, totalPages) => {
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.slate);
  doc.text(
    `Generated by JobProof · Page ${pageNumber} of ${totalPages}`,
    PAGE.margin,
    PAGE.height - 8
  );
};

const addSectionTitle = (doc, title, y) => {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...COLORS.navy);
  doc.text(title, PAGE.margin, y);
  return y + 5;
};

const addTable = (doc, title, rows, y) => {
  const cleanRows = rows.filter((row) => {
    return row.some((cell) => cell !== undefined && cell !== null);
  });

  if (!cleanRows.length) return y;

  const titleY = addSectionTitle(doc, title, y);

  autoTable(doc, {
    startY: titleY,
    head: [["Field", "Details"]],
    body: cleanRows,
    theme: "grid",
    margin: {
      left: PAGE.margin,
      right: PAGE.margin,
    },
    styles: {
      font: "helvetica",
      fontSize: 9,
      cellPadding: 3,
      textColor: COLORS.navy,
      lineColor: COLORS.border,
      lineWidth: 0.2,
      valign: "top",
    },
    headStyles: {
      fillColor: COLORS.blue,
      textColor: COLORS.white,
      fontStyle: "bold",
    },
    columnStyles: {
      0: {
        cellWidth: 48,
        fontStyle: "bold",
        fillColor: COLORS.lightSlate,
      },
      1: {
        cellWidth: "auto",
      },
    },
  });

  return doc.lastAutoTable.finalY + 10;
};

const addTextBox = (doc, title, text, y) => {
  const cleanText = formatValue(text, "No details provided.");
  const maxWidth = PAGE.width - PAGE.margin * 2;
  const lines = doc.splitTextToSize(cleanText, maxWidth - 8);

  const boxHeight = Math.max(18, lines.length * 5 + 14);

  if (y + boxHeight > PAGE.height - 20) {
    doc.addPage();
    y = 20;
  }

  y = addSectionTitle(doc, title, y);

  doc.setDrawColor(...COLORS.border);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(PAGE.margin, y, maxWidth, boxHeight, 2, 2, "FD");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.navy);
  doc.text(lines, PAGE.margin + 4, y + 8);

  return y + boxHeight + 10;
};

const convertImageToDataUrl = async (imageUrl) => {
  if (!imageUrl || typeof imageUrl !== "string") return null;

  if (imageUrl.startsWith("data:image")) {
    return imageUrl;
  }

  try {
    const response = await fetch(imageUrl);
    const blob = await response.blob();

    return await new Promise((resolve) => {
      const reader = new FileReader();

      reader.onloadend = () => {
        resolve(reader.result);
      };

      reader.onerror = () => {
        resolve(null);
      };

      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.warn("Could not load image for PDF:", error);
    return null;
  }
};

const addImageGrid = async (doc, title, photos = [], y) => {
  const validPhotos = photos.filter(Boolean);

  if (!validPhotos.length) {
    return y;
  }

  if (y > PAGE.height - 70) {
    doc.addPage();
    y = 20;
  }

  y = addSectionTitle(doc, title, y);

  const imageWidth = 84;
  const imageHeight = 58;
  const gap = 10;
  const leftX = PAGE.margin;
  const rightX = PAGE.margin + imageWidth + gap;

  let x = leftX;

  for (let index = 0; index < validPhotos.length; index += 1) {
    if (y + imageHeight + 12 > PAGE.height - 20) {
      doc.addPage();
      y = 20;
      y = addSectionTitle(doc, title, y);
      x = leftX;
    }

    const photoUrl = validPhotos[index];
    const imageData = await convertImageToDataUrl(photoUrl);

    doc.setDrawColor(...COLORS.border);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(x, y, imageWidth, imageHeight, 2, 2, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.slate);
    doc.text(`${title.replace(" photos", "")} photo ${index + 1}`, x + 3, y + 5);

    if (imageData) {
      try {
        doc.addImage(imageData, "JPEG", x + 3, y + 8, imageWidth - 6, imageHeight - 11);
      } catch {
        try {
          doc.addImage(imageData, "PNG", x + 3, y + 8, imageWidth - 6, imageHeight - 11);
        } catch (error) {
          console.warn("Could not add image to PDF:", error);
          doc.setFont("helvetica", "normal");
          doc.setFontSize(8);
          doc.text("Image could not be loaded.", x + 6, y + 30);
        }
      }
    } else {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.text("Image could not be loaded.", x + 6, y + 30);
    }

    if (x === leftX) {
      x = rightX;
    } else {
      x = leftX;
      y += imageHeight + 12;
    }
  }

  if (x !== leftX) {
    y += imageHeight + 12;
  }

  return y + 2;
};

const addHeader = async (doc, reportData) => {
  doc.setFillColor(...COLORS.navy);
  doc.rect(0, 0, PAGE.width, 36, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.white);
  doc.text("JOBPROOF", PAGE.margin, 15);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Professional job completion report", PAGE.margin, 22);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(formatValue(reportData.reportNumber, "Report number pending"), PAGE.margin, 30);

  const status = reportData.status || "pending";
  const statusColor = getStatusColor(status);

  doc.setFillColor(...statusColor);
  doc.roundedRect(150, 11, 42, 10, 2, 2, "F");

  doc.setFontSize(8);
  doc.setTextColor(...COLORS.white);
  doc.text(formatStatusLabel(status).toUpperCase(), 171, 17.5, {
    align: "center",
  });

  if (reportData.businessLogo) {
    const logoData = await convertImageToDataUrl(reportData.businessLogo);

    if (logoData) {
      try {
        doc.addImage(logoData, "JPEG", 172, 23, 20, 10);
      } catch {
        try {
          doc.addImage(logoData, "PNG", 172, 23, 20, 10);
        } catch {
          // Ignore logo errors.
        }
      }
    }
  }

  return 48;
};

export const generatePDF = async (reportData = {}) => {
  const doc = new jsPDF("p", "mm", "a4");

  let y = await addHeader(doc, reportData);

  y = addTable(
    doc,
    "Business details",
    [
      ["Business name", formatValue(reportData.businessName)],
      ["Business email", formatValue(reportData.businessEmail)],
      ["Business phone", formatValue(reportData.businessPhone)],
      ["Prepared by", formatValue(reportData.workerName)],
    ],
    y
  );

  y = addTable(
    doc,
    "Client and job details",
    [
      ["Status", formatStatusLabel(reportData.status || "pending")],
      ["Client", formatValue(reportData.clientDisplayName || reportData.clientName)],
      ["Client company", formatValue(reportData.clientCompanyName)],
      ["Contact person", formatValue(reportData.clientContactPerson)],
      ["Client email", formatValue(reportData.clientEmail)],
      ["Client phone", formatValue(reportData.clientPhone)],
      [
        "Job address",
        formatValue(reportData.clientAddressSnapshot || reportData.jobAddress),
      ],
      ["Job date", formatDate(reportData.jobDate)],
      ["Start time", formatTime(reportData.startingHour)],
      ["Finish time", formatTime(reportData.finishHour)],
      ["Total hours", formatValue(reportData.totalHours, "0")],
      ["Service type", formatValue(reportData.serviceType)],
      ["Access notes", formatValue(reportData.clientAccessNotes)],
    ],
    y
  );

  const teamRows =
    reportData.teamInvolved && reportData.teamInvolved.length > 0
      ? reportData.teamInvolved.map((member, index) => [
          `Team member ${index + 1}`,
          formatTeamMember(member),
        ])
      : [["Team involved", "No team members listed."]];

  y = addTable(doc, "Team involved", teamRows, y);

  y = addTextBox(doc, "Work completed", reportData.workCompleted, y);
  y = addTextBox(doc, "Issues found", reportData.issuesFound, y);
  y = addTextBox(doc, "Recommendations", reportData.recommendations, y);

  y = await addImageGrid(doc, "Before photos", reportData.beforePhotos || [], y);
  y = await addImageGrid(doc, "After photos", reportData.afterPhotos || [], y);

  const totalPages = doc.internal.getNumberOfPages();

  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    addPageFooter(doc, page, totalPages);
  }

  const fileName = `${safeFileName(reportData.reportNumber || "job-report")}.pdf`;

  doc.save(fileName);
};